[package]
name = "sensible_widgets"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
chunks-rs = "0.7.3"
rayon = "1.10.0"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
tokio = { version = "1.42.0", features = ["full"] }
zbus = "5.3.0"
